steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/rendertron/rendertron:latest', '.']
images: ['asia-northeast1-docker.pkg.dev/$PROJECT_ID/rendertron/rendertron:latest']
